arch: arm64

sudo: required

language: bash

services:
  - docker

script:
  - docker run --rm --entrypoint=cat alpine/git:v2.30.2 /etc/os-release
  - docker run --rm --entrypoint=apk alpine/git:v2.30.2 add bash
