arch: arm64

sudo: required

language: bash

services:
  - docker

script:
  - docker run --rm --entrypoint=cat alpine/git:1.0.30 /etc/os-release
  - docker run --rm --entrypoint=apk alpine/git:1.0.30 add bash
