arch: arm64

sudo: required

language: bash

services:
  - docker

script:
  - docker run --rm --entrypoint="sh" alpine/git cat /etc/*release
  - docker run --rm --entrypoint="apk" alpine/git add bash
