arch: arm64

sudo: required

language: bash

services:
  - docker

script:
  - docker run --rm --entrypoint=cat alpine/git:test-only /etc/os-release
  - docker run --rm --entrypoint=apk alpine/git:test-only add bash
